---
kind: pipeline
type: docker
name: client

steps:
  - name: build
    image: golang:1.17
    environment:
      GO111MODULE: on
    commands:
      - sh scripts/build_all.sh
      - sh scripts/bundle.sh

  - name: publish
    image: plugins/github-release
    settings:
      files:
        - release/dns_*.tar.gz
        - release/dns_*_checksums.txt
      api_key:
        from_secret: github_api_key
    when:
      event: [ tag ]

trigger:
  event:
    - tag
    - push
